# Generated by Django 3.1.7 on 2021-03-09 10:21

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210309_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))])), ('simple_richtext', streams.blocks.SimpleRichtextBlock()), ('full_richtext', streams.blocks.RichtextBlock()), ('codeblock', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('csharp', 'C#'), ('cpp', 'C++'), ('css', 'CSS'), ('django', 'Django/Jinja2'), ('go', 'Go'), ('html', 'HTML'), ('javascript', 'Javascript'), ('jsx', 'React JSX'), ('tsx', 'React TSX'), ('json', 'JSON'), ('php', 'PHP'), ('python', 'Python'), ('scss', 'SCSS'), ('sql', 'SQL')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))], blank=True, null=True),
        ),
    ]
