# Generated by Django 3.1.7 on 2021-05-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210312_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdetailpage',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
