# Generated by Django 3.1.7 on 2021-05-09 05:40

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_text', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))])), ('simple_richtext', streams.blocks.SimpleRichtextBlock()), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
                ('content', wagtail.core.fields.StreamField([('projectblock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Project title', required=True)), ('content', wagtail.core.blocks.TextBlock(help_text='Project detail', required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Project link', required=False)), ('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt', wagtail.core.blocks.CharBlock(max_length=100, required=True))])))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio Page',
                'verbose_name_plural': 'Portfolio Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
