# Generated by Django 3.1.7 on 2021-05-14 22:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=wagtail.core.fields.StreamField([('projectblock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Project title', required=True)), ('uid', wagtail.core.blocks.CharBlock(help_text='Unique Project ID', required=True)), ('content', wagtail.core.blocks.TextBlock(help_text='Project detail', required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Project link', required=False)), ('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt', wagtail.core.blocks.CharBlock(max_length=100, required=True))])))]))], blank=True, null=True),
        ),
    ]
